/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as InvestimentosRouteImport } from './routes/investimentos'
import { Route as EntradasRouteImport } from './routes/entradas'
import { Route as DicasRouteImport } from './routes/dicas'
import { Route as DespesasFixasRouteImport } from './routes/despesas-fixas'
import { Route as CartoesRouteImport } from './routes/cartoes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicSendFixedExpenseRemindersRouteImport } from './routes/api/public/send-fixed-expense-reminders'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestimentosRoute = InvestimentosRouteImport.update({
  id: '/investimentos',
  path: '/investimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const EntradasRoute = EntradasRouteImport.update({
  id: '/entradas',
  path: '/entradas',
  getParentRoute: () => rootRouteImport,
} as any)
const DicasRoute = DicasRouteImport.update({
  id: '/dicas',
  path: '/dicas',
  getParentRoute: () => rootRouteImport,
} as any)
const DespesasFixasRoute = DespesasFixasRouteImport.update({
  id: '/despesas-fixas',
  path: '/despesas-fixas',
  getParentRoute: () => rootRouteImport,
} as any)
const CartoesRoute = CartoesRouteImport.update({
  id: '/cartoes',
  path: '/cartoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendFixedExpenseRemindersRoute =
  ApiPublicSendFixedExpenseRemindersRouteImport.update({
    id: '/api/public/send-fixed-expense-reminders',
    path: '/api/public/send-fixed-expense-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cartoes': typeof CartoesRoute
  '/despesas-fixas': typeof DespesasFixasRoute
  '/dicas': typeof DicasRoute
  '/entradas': typeof EntradasRoute
  '/investimentos': typeof InvestimentosRoute
  '/relatorios': typeof RelatoriosRoute
  '/api/public/send-fixed-expense-reminders': typeof ApiPublicSendFixedExpenseRemindersRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cartoes': typeof CartoesRoute
  '/despesas-fixas': typeof DespesasFixasRoute
  '/dicas': typeof DicasRoute
  '/entradas': typeof EntradasRoute
  '/investimentos': typeof InvestimentosRoute
  '/relatorios': typeof RelatoriosRoute
  '/api/public/send-fixed-expense-reminders': typeof ApiPublicSendFixedExpenseRemindersRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cartoes': typeof CartoesRoute
  '/despesas-fixas': typeof DespesasFixasRoute
  '/dicas': typeof DicasRoute
  '/entradas': typeof EntradasRoute
  '/investimentos': typeof InvestimentosRoute
  '/relatorios': typeof RelatoriosRoute
  '/api/public/send-fixed-expense-reminders': typeof ApiPublicSendFixedExpenseRemindersRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/cartoes'
    | '/despesas-fixas'
    | '/dicas'
    | '/entradas'
    | '/investimentos'
    | '/relatorios'
    | '/api/public/send-fixed-expense-reminders'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/cartoes'
    | '/despesas-fixas'
    | '/dicas'
    | '/entradas'
    | '/investimentos'
    | '/relatorios'
    | '/api/public/send-fixed-expense-reminders'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/cartoes'
    | '/despesas-fixas'
    | '/dicas'
    | '/entradas'
    | '/investimentos'
    | '/relatorios'
    | '/api/public/send-fixed-expense-reminders'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CartoesRoute: typeof CartoesRoute
  DespesasFixasRoute: typeof DespesasFixasRoute
  DicasRoute: typeof DicasRoute
  EntradasRoute: typeof EntradasRoute
  InvestimentosRoute: typeof InvestimentosRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ApiPublicSendFixedExpenseRemindersRoute: typeof ApiPublicSendFixedExpenseRemindersRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investimentos': {
      id: '/investimentos'
      path: '/investimentos'
      fullPath: '/investimentos'
      preLoaderRoute: typeof InvestimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entradas': {
      id: '/entradas'
      path: '/entradas'
      fullPath: '/entradas'
      preLoaderRoute: typeof EntradasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dicas': {
      id: '/dicas'
      path: '/dicas'
      fullPath: '/dicas'
      preLoaderRoute: typeof DicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despesas-fixas': {
      id: '/despesas-fixas'
      path: '/despesas-fixas'
      fullPath: '/despesas-fixas'
      preLoaderRoute: typeof DespesasFixasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartoes': {
      id: '/cartoes'
      path: '/cartoes'
      fullPath: '/cartoes'
      preLoaderRoute: typeof CartoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-fixed-expense-reminders': {
      id: '/api/public/send-fixed-expense-reminders'
      path: '/api/public/send-fixed-expense-reminders'
      fullPath: '/api/public/send-fixed-expense-reminders'
      preLoaderRoute: typeof ApiPublicSendFixedExpenseRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CartoesRoute: CartoesRoute,
  DespesasFixasRoute: DespesasFixasRoute,
  DicasRoute: DicasRoute,
  EntradasRoute: EntradasRoute,
  InvestimentosRoute: InvestimentosRoute,
  RelatoriosRoute: RelatoriosRoute,
  ApiPublicSendFixedExpenseRemindersRoute:
    ApiPublicSendFixedExpenseRemindersRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
